name: Rubocop and Rspec 
on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: mer-team/rabbitmq-mng-action@v1.2
        with:
          RABBITMQ_USER: 'guest'
          RABBITMQ_PASS: 'guest'
          RABBITMQ_PORT: 5672
          RABBITMQ_MNG_PORT: 15672
          RABBITMQ_TAG: '3-management-alpine'
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-event_source-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            ${{ runner.os }}-event_source-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Run rubocop
        run: |
          bundle exec rubocop
      - name: Run rspec
        run: |
          bundle exec rspec