name: full check suite
on:
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1
      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: v1-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            v1-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: bundle install
        run: |
          gem update --system
          bundle config path vendor/bundle
          bundle check || bundle install
      - name: Run rubocop
        run: |
          git config diff.renameLimit 800
          git fetch --no-tags --depth=1 origin master
          bundle exec rubocop-git origin/master | grep "no offenses detected"
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1
      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: v1-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            v1-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: bundle install
        run: |
          gem update --system
          bundle config path vendor/bundle
          bundle check || bundle install
      - name: Run rspec
        run: bundle exec rspec